[build]
  command = "npx prisma generate && npx prisma db push --skip-generate && node prisma/seed.js && node prisma/seed-blog.js && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
