/**
 * One-off: dumps all data from the local SQLite dev.db into Postgres INSERT
 * statements, formatted as a Netlify DB migration file.
 * Usage: node prisma/dump-to-sql.js > netlify/database/migrations/<ts>_seed_data/migration.sql
 */
const { DatabaseSync } = require('node:sqlite');
const path = require('path');

const db = new DatabaseSync(path.join(__dirname, 'dev.db'), { readOnly: true });

const DATE_COLUMNS = new Set(['createdAt', 'updatedAt', 'publishDate']);

function q(v, col) {
  if (v === null || v === undefined) return 'NULL';
  if (DATE_COLUMNS.has(col) && typeof v === 'number') {
    return `'${new Date(v).toISOString()}'`;
  }
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return `'${v.replace(/'/g, "''")}'`;
  throw new Error('unexpected type ' + typeof v);
}

const tables = [
  'Settings',
  'Admin',
  'Brand',
  'Car',
  'CarImage',
  'CarVideo',
  'BlogCategory',
  'BlogPost',
  '_BlogPostToCar',
  'Inquiry',
];

console.log('-- Dream Cars data migrated from SQLite dev.db');
console.log('-- Generated by prisma/dump-to-sql.js\n');

for (const table of tables) {
  const rows = db.prepare(`SELECT * FROM "${table}"`).all();
  if (rows.length === 0) {
    console.log(`-- ${table}: no rows\n`);
    continue;
  }
  const cols = Object.keys(rows[0]);
  const colList = cols.map((c) => `"${c}"`).join(', ');
  console.log(`-- ${table} (${rows.length} rows)`);
  for (const row of rows) {
    const values = cols.map((c) => q(row[c], c)).join(', ');
    console.log(`INSERT INTO "${table}" (${colList}) VALUES (${values});`);
  }
  console.log('');
}

db.close();
